---
title: "Cross-validation test"
author: "Joshua Rosenberg"
date: "7/1/2017"
output:
  pdf_document: default
  html_document: default
---

# Loading data, setting up 

```{r, eval = T, echo = F, message = F, warning = F, error = F}
library(prcr)
library(tidyverse)

ctk <- read_csv("~/downloads/ctk.csv")

esm_df <- haven::read_sav('/Users/joshuarosenberg/Dropbox/1_Research/SciMo/JRST\ MEP\ Paper\ Final\ Docs/esm_data.sav')

to_remove <- esm_df$stud_ID == "AXR050594" & esm_df$month == 10 & esm_df$day == 20 & esm_df$year == 8 & esm_df$signal == 2 # removing 10/20/8, ID = "AXR050594", second beeper
esm_df <- esm_df[!to_remove, ]

df <- esm_df %>%
    mutate(behavioral_scale = ifelse(!is.na(conc) & !is.na(hardwk), (conc + hardwk) / 2, 
                                     ifelse(is.na(conc), hardwk, conc)),
           cognitive_scale = ifelse(!is.na(imp_y) & !is.na(imp_fut), (imp_y + imp_fut) / 2, 
                                    ifelse(is.na(imp_y), imp_fut, imp_y)),
           affective_scale = ifelse(!is.na(enjoy) & !is.na(interest), (enjoy + interest) / 2, 
                                    ifelse(is.na(enjoy), interest, enjoy)))

df <- df[ctk$ctk, ]
```

# Cluster data

```{r}
x <- create_profiles(df,
                     behavioral_scale,
                     cognitive_scale,
                     affective_scale,
                     n_profiles = 6,
                     to_center = T,
                     to_scale = T)

plot(x)
```

# Cross-validate 

```{r}

cv_output <- cross_validate(df,
                            behavioral_scale,
                            cognitive_scale,
                            affective_scale,
                            n_profiles = 6,
                            to_center = T,
                            to_scale = T,
                            k = 30)

knitr::kable(cv_output)
```