---
title: "Introduction to cluster analysis-based use of prcr"
author: "Joshua Rosenberg"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
vignette: |
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
# Example 
  
In this example using the built-in to `prcr` dataset `pisaUSA15`. Specifically, we use composite variables for broad interest, enjoyment, instrumental motivation, and self-efficacy. More information on these and other items can be found at [this link](www.oecd.org/pisa/data/2015database/Codebook_CMB.xlsx).
  
```{r, echo = F}
devtools::load_all(".")
```

```{r, eval = F}
library(prcr)
```

```{r, eval = T}
df <- pisaUSA15
m3 <- create_profiles_cluster(df, broad_interest, enjoyment, instrumental_mot, self_efficacy, n_profiles = 3)
summary(m3)
plot_profiles(m3$.data)
```

Comparison of R-squared values can be carried out as follows:

```{r, message = F, eval = T}
estimate_r_squared(df, broad_interest, enjoyment, instrumental_mot, self_efficacy)
```